sudo : required
services :
    - docker

before_install :
    - docker build -t arvindpalli/docker-react -f Dockerfile.dev .

script:
    - docker run arvindpalli/docker-react npm run test -- --coverage

